### ISSUE TITLE
`Jump to link` fails in Source Mode

### ISSUE THREAD

**Issue by chrisgrieser** [mrjackphil/obsidian-jump-to-link#31]
it does nothing, and I get the following console output

```log
app.js:1 TypeError: cmEditor.coordsChar is not a function
    at getVisibleLineText (eval at <anonymous> (app.js:1:1433712), <anonymous>:47:37)
    at SourceLinkProcessor.getSourceLinkHints (eval at <anonymous> (app.js:1:1433712), <anonymous>:308:41)
    at SourceLinkProcessor.init (eval at <anonymous> (app.js:1:1433712), <anonymous>:316:32)
    at JumpToLink.handleJumpToLink (eval at <anonymous> (app.js:1:1433712), <anonymous>:430:88)
    at JumpToLink.action (eval at <anonymous> (app.js:1:1433712), <anonymous>:569:22)
    at WR (app.js:1:1552123)
    at e.executeCommandById (app.js:1:1553368)
    at eval (eval at <anonymous> (app.js:1:1433712), <anonymous>:74:11668)
    at e.o [as executeCommandById] (eval at <anonymous> (app.js:1:1433712), <anonymous>:23:77225)
    at T.eval (eval at <anonymous> (app.js:1:1433712), <anonymous>:15:16522)
```

**Comment by mrjackphil** [comment]
Ooops... I even didn't know in exists in CM6 :) Give me couple minutes.

**Comment by chrisgrieser** [comment]
thanks!

**Comment by ejf071189** [comment]
Did this fix actually work? I'm still getting console errors in editor mode using regex:
```
common.ts:11 Uncaught TypeError: cmEditor.coordsChar is not a function
    at getVisibleLineText (eval at <anonymous> (app.js:1), <anonymous>:47:37)
    at RegexpProcessor.getVisibleContent (eval at <anonymous> (app.js:1), <anonymous>:175:37)
    at RegexpProcessor.init (eval at <anonymous> (app.js:1), <anonymous>:168:40)
    at JumpToLink.handleJumpToRegex (eval at <anonymous> (app.js:1), <anonymous>:463:95)
    at JumpToLink.action (eval at <anonymous> (app.js:1), <anonymous>:572:22)
    at WR (app.js:1)
    at t.onChooseItem (app.js:1)
    at t.onChooseSuggestion (app.js:1)
    at t.selectSuggestion (app.js:1)
    at e.useSelectedItem (app.js:1)
```

and regular jump to link:
```
common.ts:11 Uncaught TypeError: cmEditor.coordsChar is not a function
    at getVisibleLineText (eval at <anonymous> (app.js:1), <anonymous>:47:37)
    at SourceLinkProcessor.getSourceLinkHints (eval at <anonymous> (app.js:1), <anonymous>:308:41)
    at SourceLinkProcessor.init (eval at <anonymous> (app.js:1), <anonymous>:316:32)
    at JumpToLink.handleJumpToLink (eval at <anonymous> (app.js:1), <anonymous>:430:88)
    at JumpToLink.action (eval at <anonymous> (app.js:1), <anonymous>:569:22)
    at WR (app.js:1)
    at t.onChooseItem (app.js:1)
    at t.onChooseSuggestion (app.js:1)
    at t.selectSuggestion (app.js:1)
    at e.useSelectedItem (app.js:1)
```

**Comment by mrjackphil** [comment]
@ejf071189 Which version of the plugin do you use? Did you try to restart Obsidian after plugin update?

**Comment by ejf071189** [comment]
Hmm it is up to date and I both tried restarting and doing a uninstall/reinstall of the plugin, neither of which worked when running the command from the palette. BUT when I did a fresh install of Obsidian on another machine, it worked as expected.

I figured out that deleting and making a new app.json fixed the issue. So perhaps there was some old legacy setting that was tripping the plugin up?

**Comment by ejf071189** [comment]
According to my community plugins list, 0.3.1.

**Comment by mrjackphil** [comment]
@ejf071189 That's odd. Current version is **0.4.4**.
